#
# Module manifest for module 'gundog' - Happy Hunting
#
# Generated by: Jan Geisbauer @jangeisbauer
#
# Generated on: 1/17/2022
#
@{
# Script module or binary module file associated with this manifest.
RootModule = 'gundog.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '304f4285-21d0-42f0-9e54-647480f80a9a'

# Author of this module
Author = 'Jan Geisbauer'

# Company or vendor of this module
CompanyName = 'emptyDC.com'

# Copyright statement for this module
Copyright = '(c) Jan Geisbauer. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft 365 Defender Hunting via PowerShell.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('Az.Accounts','Az.KeyVault')

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Start-Gundog','Get-AllAlertsByTenant','Get-GunDogHunt','Get-Vulnerabilities','Get-AllAlertsAllTenants','Get-AllAlertsAllTenantsRefresh','Get-MultiTenantHunting','Set-GundogConfig')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @('Start-Gundog')

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()
}